domain: nhsx.github.io
url: https://nhsx.github.io
baseurl: /nhsx-internship-projects/
repository: nhsx/nhsx-internship-projects
title: NHS England Data Science PhD Internships
description: NHS England PhD Internship
email: datascience@nhs.net
github_username: nhsx
plugins:
  - jemoji

